//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ResourceManager rm = new ResourceManager(&quot;resource&quot;, Assembly.GetExecutingAssembly());
        ///byte[] appBytes = (byte[])rm.GetObject(&quot;%appname%&quot;);
        ///
        /////Loading App
        ///int appSize = %appsize%;
        ///MemoryStream memStr = new MemoryStream(appBytes);
        ///var gStream = new %mode%;
        ///
        ///
        ///
        ///byte[] tAppBytes = new byte[appSize];
        ///
        ///gStream.Read(tAppBytes, 0, appSize);
        ///memStr.Close();
        ///gStream.Close();
        ///
        /////End Loading App.
        /// </summary>
        public static string AppMethod {
            get {
                return ResourceManager.GetString("AppMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        /////nothing passed on yet.
        ///var assemb = Assembly.Load(tAppBytes);
        ///tAppBytes = null; 
        ///GC.Collect();
        ///
        ///try {
        ///	assemb.EntryPoint.Invoke(null, new object[] { new string[0]});
        ///} catch(Exception ex) {
        ///	Console.WriteLine(&quot;Invoke Main error ! {0}&quot;, ex.Message);
        ///}
        ///.
        /// </summary>
        public static string AppMethodEnd {
            get {
                return ResourceManager.GetString("AppMethodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [assembly: AssemblyTitle(&quot;&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyProduct(&quot;&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright ©&quot;)]
        ///[assembly: AssemblyTrademark(&quot;&quot;)]
        ///[assembly: AssemblyCulture(&quot;&quot;)]
        ///
        ///// Version information for an assembly consists of the following four values:
        /////
        /////      Major Version
        /////      Minor Version 
        /////      Build Number
        /////      Revision
        /////
        ///// You can specify all the values or you can defa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
    }
}
