//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Load packed intro from resource
        ///
        /////ResourceManager rm = new ResourceManager(&quot;resource&quot;, Assembly.GetExecutingAssembly());
        /////byte[] appBytes = (byte[])rm.GetObject(&quot;%appname%&quot;);
        ///
        /////Load 64k exe from embbeded resource
        ///var memStr = Assembly.GetExecutingAssembly().GetManifestResourceStream(&quot;Packed.exetemp_c.dat&quot;);
        ///
        /////Console.WriteLine(&quot;memStr:&quot;+ memStr.Length);
        ///
        /////Loading App
        ///int appSize = %appsize%;
        ///var gStream = new %mode%;
        ///byte[] tAppBytes = new byte[appSize];
        ///
        ///gStream.Read(tAppBytes, 0, app [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppMethod {
            get {
                return ResourceManager.GetString("AppMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /////Start Packed.exe
        ///var assemb = Assembly.Load(tAppBytes);
        ///assemb.EntryPoint.Invoke(null, null);
        ///.
        /// </summary>
        public static string AppMethodEnd {
            get {
                return ResourceManager.GetString("AppMethodEnd", resourceCulture);
            }
        }
    }
}
